### ISSUE TITLE
Analogue of `adaptError` from MonadError for Handle

### ISSUE THREAD

**Issue by susliko** [TinkoffCreditSystems/tofu#112]
It would be nice to have something like 
```
def adaptError[A](fa: F[A])(pf: PartialFunction[E, E]): F[A]
```
in `Handle` typeclass

**Comment by atapin** [comment]
@susliko @Odomontois 
this would imply `Handle` to depend on `Raise`, which seems to contradict the idea of tofu. what about making a separate typeclass for `adaptError` behavior?

**Comment by Odomontois** [comment]
@atapin In your opinion aren't `Errors` suffice?

**Comment by atapin** [comment]
@Odomontois I meant the following: cats' `MonadError.adaptError` semantics is 'transform and raise'. Thus `Handle` doesn't look a good place to declare this behavior, as we have `Raise`. 
Now I revisited the code, and I think `Raise` could be a good place.
Btw doesn't the requested behavior look like a compositions of raise upcast and handle downcast?
