### ISSUE TITLE
Function allowing to get back into exceptional context in `RestoreTo`

### ISSUE THREAD

**Issue by oskin1** [TinkoffCreditSystems/tofu#117]
Wouldn't it be useful to have a function allowing to get back from `G[_]` to `F[_]` in `RestoreTo`?

**Comment by Odomontois** [comment]
LIke `RestoreTo[F, G, E] extends Lift[G, F]` ?

**Comment by oskin1** [comment]
> LIke `RestoreTo[F, G, E] extends Lift[G, F]` ?

Though I'm not sure whether such hierarchy is intuitive. Maybe it would be enough to add new method with some meaningful name (in context of `RestoreTo`)?
