### ISSUE TITLE
Possibly fix unstable concurrent test for ReadWrite

### ISSUE THREAD

**Issue by Odomontois** [TinkoffCreditSystems/tofu#13]
[this build](https://travis-ci.com/TinkoffCreditSystems/tofu/jobs/233995455 ) was unsuccessful  due to unpredictable fiber scheduling, it would be nice to search the way to stabilize it

**Comment by Phill101** [comment]
Well, it's non deterministic stuff.
There is no other way but increase sleeping time, I guess (correct me).
But 10 millis should be enough.

**Comment by Phill101** [comment]
I increased it to 20 millis
