### ISSUE TITLE
Provide instances of loggable for java.time data classes

### ISSUE THREAD

**Issue by mehakun** [TinkoffCreditSystems/tofu#315]
It would be nice to have instances of those classes. 
Maybe new API for formatting dates could be  born from this issue :)

**Comment by catostrophe** [comment]
They've already been added. But what I don't like is the default formatter.

**Comment by mehakun** [comment]
Not all of them though :) 
For example, there is an open PR: https://github.com/TinkoffCreditSystems/tofu/pull/316
And wouldn't it be easier to add all classes instead of one by one?

**Comment by pomadchin** [comment]
There is already https://github.com/TinkoffCreditSystems/tofu/blob/ce1171f8bc9d18fa5a2beb6f2a2ee9c99b8349d7/core/src/main/scala/tofu/common/time.scala#L80-L90 

Mb we can consolidate `time` typeclasses somehow?

**Comment by Odomontois** [comment]
Can we close this now? @mehakun

**Comment by Odomontois** [comment]
We can open new issue regarding format, and maybe refactoring some qualities to the common typeclass such as TimeData

**Comment by mehakun** [comment]
@Odomontois I it can be closed, currently discussed problem is kinda unrelated to the issue, I agree.
