### ISSUE TITLE
Conflicting tofu.Errors implicit inference

### ISSUE THREAD

**Issue by susliko** [TinkoffCreditSystems/tofu#398]
[Error instance hierarchy refactoring](https://github.com/TinkoffCreditSystems/tofu/pull/382)
 led to imposibility of `.raise` syntax usage without specifying types explicitly if there is at least an `ApplicativeError` instance in the context.

https://scastie.scala-lang.org/PyLHexCiQG2TtIkey41dZQ

**Comment by Odomontois** [comment]
I believe it's not conflict, it's just legacy `RaiseContravariant` still used in some syntax is not a subtype of ErrorBase, so prismatic instances are not found.
We must just replace all RaiseContravariant in syntax ASAP
