### ISSUE TITLE
Need interop with cats-mtl

### ISSUE THREAD

**Issue by catostrophe** [TinkoffCreditSystems/tofu#431]
Some libs depend on cats-mtl typeclasses. It would be great to provide a module with conversions from tofu typeclasses to cats-mtl.

**Comment by Ssstlis** [comment]
What kind of conversions do we need? Prefer to explicit or implicit?

**Comment by catostrophe** [comment]
We need to derive Ask/Local given Applicative+HasContext/HasLocal.
The same approach should be applied for error handling conversions.

**Comment by Ssstlis** [comment]
Do you mean that we should also add interop between FunctorRaise/Raise and ApplicativeHandle/Handle?
