### ISSUE TITLE
Improve Logging documentation

### ISSUE THREAD

**Issue by Z1kkurat** [TinkoffCreditSystems/tofu#471]
Worth mentioning:
* annotations (`@hidden`, etc.)
* presence of `derevo` integration
* ELKLayout description with usage in context of logback.xml
* more detailed description of contextual logging - explanation for leveraging slf4j marker APIs for passing context values (including usage in ELKLayout)
* more complex examples of initializing logging classes and passing them as dependencies to other components (with multiple effects)

Probably I'll take this.

**Comment by mehakun** [comment]
Also  tofu.logging.LoggingCompanion is good candidate. Here is small example of usage:
```
import tofu.logging.LoggingCompanion

trait FooService[F[_]] {
//…
}
object FooService extends LoggingCompanion[FooService] {
  def make[F[_]: Monad : Monяd: FooService.Log]: FooService[F] = ???
}
//FooService.Log = ServiceLogging[FooService[Any]]
```
And it also has caveat:
When you are calling Logs::forService you should call `Logs.forService[F, FooService[Any]]` not `Logs.forService[F, FooService[F]]`
