### ISSUE TITLE
Derived RepresentableK should proxy all methods including implemented

### ISSUE THREAD

**Issue by ioaoue** [TinkoffCreditSystems/tofu#487]
The current implementation in HigherKindedMacros only proxies unimplemented methods. Because of this, the behavior of the class may change when wrapping it in Embed:
```scala
import tofu._
import tofu.higherKind._

trait Service[F[_]] {
  def defaultValue: F[String]
  def value: F[String] = defaultValue
}

object Service {
  implicit val representableK: RepresentableK[Service] = derived.genRepresentableK[Service]
}

final class ServiceImpl extends Service[Option] {
  override def defaultValue: Option[String] = None
  override def value: Option[String] = Some("value")
}


val impl = new ServiceImpl()
impl.value // Some("value")

val embedded = Embed.of[Service, Option](Some(impl))
embedded.value // None
```
https://scastie.scala-lang.org/qyV8mImjQTGuw65bOPa5xw

**Comment by ioaoue** [comment]
This affects Loggable in tofu-0.9.0: when logging through slf4j, all exceptions are wrapped in LoggedThrowable.
https://scastie.scala-lang.org/Hc8loyy3R6O1mVW5UcauxQ

**Comment by catostrophe** [comment]
When I did #424 I was in the delirium of brainfever. Why did nobody stop me?
