### ISSUE TITLE
Bifunctor alternative for Env?

### ISSUE THREAD

**Issue by Z1kkurat** [TinkoffCreditSystems/tofu#57]
Separate type for typed error (not fixed to Throwable) can be useful in many situations, including expressing absence of error (as `Nothing`) as well as representing some domain errors.
Monix contributors are already working on BIO alternative to Task (https://github.com/monix/monix-bio).
Should we provide such an alternative to Env? Probably it would be wiser to build it upon Monix BIO implementation (or not).

**Comment by Odomontois** [comment]
The trouble here is how to separate two kinds of errors in the API.
I can imagine special encoding where business error is sunken inside the special box, implementing Throwable.
But we need to duplicate methods for throwing\handing as well as own `Case` constructor for brackets.

**Comment by Z1kkurat** [comment]
Trying to handle this here https://github.com/TinkoffCreditSystems/tofu/pull/84

**Comment by Odomontois** [comment]
Closing this, since PR is merged.
Looking forward to more specific issues targeting #84 implementation.
