### ISSUE TITLE
Execute instance for ZIO

### ISSUE THREAD

**Issue by susliko** [TinkoffCreditSystems/tofu#82]
It would be nice to add `tofu.Execute` typeclass intance for `ZIO`

**Comment by Odomontois** [comment]
Also it would be nice to remove `Async` mention inside `Execute`

**Comment by Z1kkurat** [comment]
Can we close this @Odomontois @susliko ?

**Comment by Odomontois** [comment]
I was hoping it will autoclose on merge #86
