### ISSUE TITLE
Typeclass for horizontal composition in optics module

### ISSUE THREAD

**Issue by road21** [TinkoffCreditSystems/tofu#87]
Given `Property[A, B]` and `Property[A, C]` we need a way to get `Property[A, (B, C)]`. 
Looks like separate typeclass and instances (at least for `Property` and `Contains`) will help.

**Comment by road21** [comment]
The problem is that horizontal composition cannot be lawful in common case. It's easy to show that there is no legal inhabitant of `p[A]: Property[A, (A, A)]` which satisfies the law: `forall X, forall x: X, x1: X, x2: X   p[X].getOpt(p[X].set(x, (x1, x2)) = Some((x1, x2))`.

**Comment by Odomontois** [comment]
Closing for now
