### ISSUE TITLE
Implement Agent

### ISSUE THREAD

**Issue by Odomontois** [TinkoffCreditSystems/tofu#95]
Implement new concurrent datatype `Agent` mostly like `RefM` from ZIO and looking like Ref + Semaphore (Atom + Gatekeeper) for everything else

It should have at least following methods 
```scala
trait Agent[F[_], A]{
  // return current value, this will never block
  def get: F[A]
  // update value with effectful transformation, wait for the new result
  def updateM(f: A => F[A]): F[A]
  // enqueue transformation, return immediately
  def fireUpdateM(f: A => F[A]): F[Unit]
  // modify value with effectful transformation, wait for the new result
  def modifyM[B](f: A => F[(A, B)]): F[B]
}
```

**Comment by susliko** [comment]
Working on this

**Comment by susliko** [comment]
PR
https://github.com/TinkoffCreditSystems/tofu/pull/107

**Comment by Odomontois** [comment]
Closing for now, since simple version has been delivered.
We'll wait for your more advanced implementation @susliko
